Address.create(address_1: "1771 Brookview Dr", address_2: "", city: "Saline", state: "MI", postal_code: "48176", user_id: User.find_by_email("quantockg@dteenergy.com").id)
Address.create(address_1: "2000 Sugarloaf Lake Road", address_2: "", city: "Chelsea", state: "MI", postal_code: "48118", user_id: User.find_by_email("braunw@dteenergy.com").id)
Address.create(address_1: "1747 Wildwood Trail", address_2: "", city: "Saline", state: "MI", postal_code: "48176", user_id: User.find_by_email("hissongm@dteenergy.com").id)
Address.create(address_1: "425 South Main Street, Suite 201", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("stewartj2@dteenergy.com").id)
Address.create(address_1: "8250 Granite Court", address_2: "", city: "Dexter", state: "MI", postal_code: "48130", user_id: User.find_by_email("stewartj2@dteenergy.com").id)
Address.create(address_1: "13120 Oakdale", address_2: "", city: "Southgate", state: "MI", postal_code: "48195", user_id: User.find_by_email("edmundss@dteenergy.com").id)
Address.create(address_1: "414 S Main St", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("zhout@dteenergy.com").id)
Address.create(address_1: "42469 Royal Lane", address_2: "N/A", city: "Clinton Township", state: "MI", postal_code: "48038", user_id: User.find_by_email("ksaur@hallrender.com").id)
Address.create(address_1: "101 W. Big Beaver Road, Ste. 200", address_2: "", city: "Troy", state: "MI", postal_code: "48084", user_id: User.find_by_email("zammitfamily4@gmail.com").id)
Address.create(address_1: "101 W. Big Beaver #200", address_2: "", city: "Troy", state: "MI", postal_code: "48084", user_id: User.find_by_email("vtornberg@kircomanix.com").id)
Address.create(address_1: "1711 Waverly", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("sobha.george@gmail.com").id)
Address.create(address_1: "122 Royal Ave.", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("lballo@comcast.net").id)
Address.create(address_1: "4600 FIRESTONE   UNIT #9", address_2: "", city: "DEARBORN", state: "MI", postal_code: "48126", user_id: User.find_by_email("pgrondziak@crain.com").id)
Address.create(address_1: "29879 RIveriside Bay cout", address_2: "29879 RIveriside Bay cout", city: "Harrison Township", state: "MI", postal_code: "48045", user_id: User.find_by_email("dcarver@crain.com").id)
Address.create(address_1: "15536 McLain", address_2: "", city: "Allen Park", state: "MI", postal_code: "48101", user_id: User.find_by_email("wkobylarz@crain.com").id)
Address.create(address_1: "574 Superior Blvd", address_2: "", city: "Wyandotte", state: "MI", postal_code: "48192", user_id: User.find_by_email("zanleys@daaa1a.org").id)
Address.create(address_1: "1694 Camelot", address_2: "", city: "Trenton", state: "MI", postal_code: "48183", user_id: User.find_by_email("padmosv@daaa1a.org").id)
Address.create(address_1: "507 N. Waverly St", address_2: "", city: "Deaborn", state: "MI", postal_code: "48128", user_id: User.find_by_email("cwiegand@kirco.com").id)
Address.create(address_1: "2825 Tall Oaks Ct ", address_2: "# 21", city: "Auburn Hills", state: "MI", postal_code: "48326", user_id: User.find_by_email("rlubinski@crain.com").id)
Address.create(address_1: "22863 Shagbark Drive", address_2: "", city: "Beverly Hills", state: "MI", postal_code: "48025", user_id: User.find_by_email("mkaczmarek@crain.com").id)
Address.create(address_1: "7770 Webster Church Rd.", address_2: "", city: "Whitmore Lake", state: "MI", postal_code: "48189", user_id: User.find_by_email("nkallek@gmail.com").id)
Address.create(address_1: "43331 St. Tropez Ct", address_2: "", city: "Sterling Heights", state: "MI", postal_code: "48314", user_id: User.find_by_email("ahugelier@crain.com").id)
Address.create(address_1: "32630 Harper Avenue", address_2: "", city: "St. Clair Shores", state: "MI", postal_code: "48082", user_id: User.find_by_email("renee_socia@toyota.com").id)
Address.create(address_1: "12220 Longtin St", address_2: "", city: "Southgate", state: "MI", postal_code: "48195", user_id: User.find_by_email("vbrna@crain.com").id)
Address.create(address_1: "48626 Thorncroft", address_2: "", city: "Macomb", state: "MI", postal_code: "48044", user_id: User.find_by_email("mkozicki@crain.com").id)
Address.create(address_1: "1333 BREWERY PARK BLVD., SUITE 200", address_2: "DAAA", city: "DETROIT", state: "MI", postal_code: "48207", user_id: User.find_by_email("fitnessdiva50@yahoo.com").id)
Address.create(address_1: "12807 Catalpa", address_2: "", city: "Southgate", state: "MI", postal_code: "48195", user_id: User.find_by_email("julikerr@gmail.com").id)
Address.create(address_1: "608 Larchlea Drive", address_2: "", city: "Birmingham", state: "MI", postal_code: "48009", user_id: User.find_by_email("jcgiroux@yahoo.com").id)
Address.create(address_1: "42459 Beechwood Drive", address_2: "", city: "Canton", state: "MI", postal_code: "48188", user_id: User.find_by_email("contactlaura20@yahoo.com").id)
Address.create(address_1: "100 Kentucky Dr", address_2: "", city: "Asheville", state: "NC", postal_code: "28806", user_id: User.find_by_email("test01@dragonbutterfly.com").id)
Address.create(address_1: "27511 Schiller", address_2: "", city: "Chesterfield", state: "MI", postal_code: "48047", user_id: User.find_by_email("heather_glowacz@polk.com").id)
Address.create(address_1: "2180 Darnell St", address_2: "", city: "Wolverine Lake", state: "MI", postal_code: "48390", user_id: User.find_by_email("dianerausch@hotmail.com").id)
Address.create(address_1: "2263 Chippenham Chase", address_2: "..", city: "Rochester Hills", state: "MI", postal_code: "48306", user_id: User.find_by_email("jamie_doman@polk.com").id)
Address.create(address_1: "3873 Aberdeen Ln", address_2: "", city: "Brighton", state: "MI", postal_code: "48114", user_id: User.find_by_email("jddavis@federalapd.com").id)
Address.create(address_1: "1304 Edgewood Ave", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("lking-moore@federalapd.com").id)
Address.create(address_1: "18835 Arleen Ct", address_2: "", city: "Livonia", state: "MI", postal_code: "48152", user_id: User.find_by_email("dhu8888@hotmail.com").id)
Address.create(address_1: "2077 Hidden Meadows Dr. ", address_2: "unnit B", city: "Walled Lake", state: "MI", postal_code: "48390", user_id: User.find_by_email("just4verno@yahoo.com").id)
Address.create(address_1: "3670 Hazelton Ave", address_2: "", city: "Rochester Hills", state: "MI", postal_code: "48307-5114", user_id: User.find_by_email("rls1206@yahoo.com").id)
Address.create(address_1: "1333 Brewery Park Blvd Suite 200", address_2: "N/A", city: "Detroit", state: "MI", postal_code: "48207", user_id: User.find_by_email("bradleyc2009@hotmail.com").id)
Address.create(address_1: "8805 Whitlock ave", address_2: "", city: "Dearborn", state: "Michigan", postal_code: "Michigan", user_id: User.find_by_email("crescentknitter@yahoo.com").id)
Address.create(address_1: "1063 Trailside Blvd.", address_2: "", city: "Wixom", state: "MI", postal_code: "48393", user_id: User.find_by_email("jgiachino@federalapd.com").id)
Address.create(address_1: "2219 Yorkshire Rd", address_2: "", city: "Birmingham", state: "MI", postal_code: "48009", user_id: User.find_by_email("caterinam@comcast.net").id)
Address.create(address_1: "1830 South Bates", address_2: "", city: "Birmingham", state: "MI", postal_code: "48009", user_id: User.find_by_email("jmskor@comcast.net").id)
Address.create(address_1: "6523 pennstone circle", address_2: "", city: "saline", state: "MI", postal_code: "48176", user_id: User.find_by_email("bevanv@dteenergy.com").id)
Address.create(address_1: "13798 Mark", address_2: "", city: "Southgate", state: "MI", postal_code: "48195", user_id: User.find_by_email("julikerr@gmail.com").id)
Address.create(address_1: "39471 Poinciana", address_2: "", city: "Sterling Heights", state: "MI", postal_code: "48313", user_id: User.find_by_email("kgieraltowski@bbdetroit.com").id)
Address.create(address_1: "4600 FIRESTONE   UNIT 9", address_2: "", city: "DEARBORN", state: "MI", postal_code: "48126", user_id: User.find_by_email("pgrondziak@crain.com").id)
Address.create(address_1: "414 S Main St", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("zhout@dteenergy.com").id)
Address.create(address_1: "7770 Webster Church Rd.", address_2: "", city: "Whitmore lake", state: "MI", postal_code: "48207", user_id: User.find_by_email("nkallek@crain.com").id)
Address.create(address_1: "31043 Mason Livonia, MI  48154", address_2: "1395 Brewery Park Blvd. suite 100", city: "Detroit", state: "MI", postal_code: "48207", user_id: User.find_by_email("brenda.e.hart-prince@census.gov").id)
Address.create(address_1: "5912 Creekside Dr", address_2: "", city: "Troy", state: "MI", postal_code: "48085", user_id: User.find_by_email("edonegan@crain.com").id)
Address.create(address_1: "101 W. Big Beaver Ste. 200", address_2: "", city: "Troy", state: "MI", postal_code: "48084", user_id: User.find_by_email("mzammit@kircomanix.com").id)
Address.create(address_1: "28124 Diesing", address_2: "", city: "Madison Heights", state: "MI", postal_code: "48071", user_id: User.find_by_email("jcarroll@crain.com").id)
Address.create(address_1: "817 Hemphill Street", address_2: "", city: "Ypsilanti", state: "MI", postal_code: "48198", user_id: User.find_by_email("godboldk@daaa1a.org").id)
Address.create(address_1: "30097 Kingsway Dr", address_2: "", city: "FarmingtonHills", state: "MI", postal_code: "48331", user_id: User.find_by_email("najarf@daaa1a.org").id)
Address.create(address_1: "38174 Saratoga Circle", address_2: "", city: "farmington hills", state: "MI", postal_code: "48331", user_id: User.find_by_email("skumar@federalapd.com").id)
Address.create(address_1: "31275 Stonewood Ct", address_2: "", city: "Farmington Hills", state: "MI", postal_code: "MI", user_id: User.find_by_email("natasha_butcher@polk.com").id)
Address.create(address_1: "xxx", address_2: "", city: "Asheville", state: "NC", postal_code: "28806", user_id: User.find_by_email("aaa@test.org").id)
Address.create(address_1: "16509 Sherwood Lane", address_2: "", city: "Northville", state: "MI", postal_code: "48168", user_id: User.find_by_email("charlotte_temple@polk.com").id)
Address.create(address_1: "4375 Eastgate", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("shakeyblue@comcast.net").id)
Address.create(address_1: " 2127 Anita", address_2: "", city: "GPW", state: "MI", postal_code: "48236", user_id: User.find_by_email("georgia_leslie@polk.com").id)
Address.create(address_1: "403 fox hills dr. n", address_2: "", city: "Bloomfield", state: "MI", postal_code: "48304", user_id: User.find_by_email("manlan_liu@polk.com").id)
Address.create(address_1: "2732 Arrowwood ct", address_2: "", city: "Sterling Heights", state: "MI", postal_code: "48314", user_id: User.find_by_email("cserra@bbdetroit.com").id)
Address.create(address_1: "33023 Grennada", address_2: "", city: "Livonia", state: "Michigan", postal_code: "Michigan", user_id: User.find_by_email("daveteds@aol.com").id)
Address.create(address_1: "27547 Bonnie Dr", address_2: "", city: "Warren", state: "MI", postal_code: "48093", user_id: User.find_by_email("gwilson@crain.com").id)
Address.create(address_1: "9877 Hawthorn Glen Dr", address_2: "", city: "Grosse Ile", state: "MI", postal_code: "48138", user_id: User.find_by_email("aferency@crain.com").id)
Address.create(address_1: "15756 Iliad St", address_2: "", city: "Detroit", state: "MI", postal_code: "MI", user_id: User.find_by_email("samcintyre@cvty.com").id)
Address.create(address_1: "1333 Gratiot Ave", address_2: "Ste. 400", city: "Detroit", state: "MI", postal_code: "48207", user_id: User.find_by_email("samcintyre@cvty.com").id)
Address.create(address_1: "20866 Botsford Dr", address_2: "Apt 5", city: "Farmington Hills", state: "MI", postal_code: "48336", user_id: User.find_by_email("fmcneill@crain.com").id)
Address.create(address_1: "2205 Boxford Road", address_2: "", city: "Trenton", state: "MI", postal_code: "48183", user_id: User.find_by_email("shiggins@crain.com").id)
Address.create(address_1: "11291 MCKINNEY", address_2: "1333 BREWERY PARK BLVD. SUITE 300", city: "DETROIT", state: "AL", postal_code: "48224", user_id: User.find_by_email("kelly.mcghee@rocketmail.com").id)
Address.create(address_1: "6017 Cedar Bend Drive", address_2: "", city: "Clarkston", state: "MI", postal_code: "48346", user_id: User.find_by_email("quevycr@dteenergy.com").id)
Address.create(address_1: "13735 E.Michigan Ave.", address_2: "", city: "clinton", state: "MI", postal_code: "49236", user_id: User.find_by_email("jansenee@dteenergy.com").id)
Address.create(address_1: "1332 Armstrong Dr.", address_2: "", city: "Chelsea", state: "MI", postal_code: "48118", user_id: User.find_by_email("laruem@dteenergy.com").id)
Address.create(address_1: "7405 Wisteria Way ", address_2: "", city: "Brighton ", state: "MI", postal_code: "48116", user_id: User.find_by_email("donna.regalado@foresee.com").id)
Address.create(address_1: "22800 Wellington Street ", address_2: "", city: "Dearborn", state: "MI", postal_code: "48124", user_id: User.find_by_email("rachel.darany@foresee.com").id)
Address.create(address_1: "438 Moran", address_2: "", city: "Grosse Pointe Farms", state: "AL", postal_code: "48236", user_id: User.find_by_email("nwrobel@autonews.com").id)
Address.create(address_1: "2832 Renfrew", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48105", user_id: User.find_by_email("lauren.helwig@gmail.com").id)
Address.create(address_1: "2026 Hunters Creek Dr", address_2: "", city: "Superior Township", state: "MI", postal_code: "48198", user_id: User.find_by_email("michelle.kryszak@foresee.com").id)
Address.create(address_1: "52136 Defever Ln", address_2: "", city: "Chesterfield", state: "MI", postal_code: "48047", user_id: User.find_by_email("townsley.cheri@gmail.com").id)
Address.create(address_1: "8790 Brooke Park", address_2: "Apt. 205", city: "Canton", state: "MI", postal_code: "48187", user_id: User.find_by_email("spatru@gmail.com").id)
Address.create(address_1: "1145 Palmer", address_2: "", city: "Plymouth", state: "MI", postal_code: "48170", user_id: User.find_by_email("katherine.bennett@foresee.com").id)
Address.create(address_1: "3623 Heeney Rd", address_2: "", city: "Stockbridge", state: "MI", postal_code: "49285", user_id: User.find_by_email("kathleen.zakrzewski@foresee.com").id)
Address.create(address_1: "11816 Earl Street", address_2: "n/a", city: "Pinckney", state: "MI", postal_code: "48169", user_id: User.find_by_email("becobrien@yahoo.com").id)
Address.create(address_1: "47085 James Rd", address_2: "", city: "Macomb", state: "MI", postal_code: "48044", user_id: User.find_by_email("rcmp62@yahoo.com").id)
Address.create(address_1: "3402 Endsleigh Lane", address_2: "", city: "Ypsilanti", state: "MI", postal_code: "48197", user_id: User.find_by_email("maggie.kalahar@foresee.com").id)
Address.create(address_1: "10091 Continental Drive", address_2: "", city: "Taylor", state: "MI", postal_code: "48180", user_id: User.find_by_email("cyndi.lyon@foresee.com").id)
Address.create(address_1: "12587 Whisper Ridge", address_2: "", city: "Freeland", state: "MI", postal_code: "48623", user_id: User.find_by_email("seibertjennifer@gmail.com").id)
Address.create(address_1: "14551 WASHBURN", address_2: "", city: "Detroit", state: "MI", postal_code: "48238", user_id: User.find_by_email("vckennedy@cvty.com").id)
Address.create(address_1: "37053 Gary", address_2: "", city: "Sterling Heights", state: "MI", postal_code: "48310", user_id: User.find_by_email("laurendarmanin@gmail.com").id)
Address.create(address_1: "8886 Mccoll Sideroad", address_2: "", city: "Brighton", state: "MI", postal_code: "48116", user_id: User.find_by_email("kdolan@crain.com").id)
Address.create(address_1: "44596 Penny Ct", address_2: "", city: "Canton", state: "MI", postal_code: "48187", user_id: User.find_by_email("rebeccamarko@hotmail.com").id)
Address.create(address_1: "1771 PLYMOUTH RD APT 305", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48105", user_id: User.find_by_email("kamaria.campbell@gmail.com").id)
Address.create(address_1: "5912 Creekside Dr", address_2: "", city: "Troy", state: "MI", postal_code: "48085", user_id: User.find_by_email("edonegan@crain.com").id)
Address.create(address_1: "13052 Sioux", address_2: "", city: "Redford", state: "MI", postal_code: "48239", user_id: User.find_by_email("lisaogrady@yahoo.com").id)
Address.create(address_1: "35758 Devereaux", address_2: "", city: "Clinton Township", state: "MI", postal_code: "48035", user_id: User.find_by_email("kciaramitaro@gmail.com").id)
Address.create(address_1: "11816 Earl Street", address_2: "", city: "Pinckney", state: "MI", postal_code: "48169", user_id: User.find_by_email("becky.obrien@foresee.com").id)
Address.create(address_1: "2102 Packard St", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("kristen.patton@foresee.com").id)
Address.create(address_1: "8837 Marquette", address_2: "", city: "Grosse Ile", state: "MI", postal_code: "48138", user_id: User.find_by_email("jennifer.brown@foreseeresults.com").id)
Address.create(address_1: "3233 Eastridge", address_2: "", city: "Dexter", state: "MI", postal_code: "48130", user_id: User.find_by_email("jeff.hughes@foresee.com").id)
Address.create(address_1: "3644 Lamplighter Drive", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("blafferty@crain.com").id)
Address.create(address_1: "5527 Cambridge Club Circle", address_2: "Apt 112", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("melissa.morse@foresee.com").id)
Address.create(address_1: "1145 Palmer", address_2: "", city: "Plymouth", state: "MI", postal_code: "48170", user_id: User.find_by_email("katie.bennett@foresee.com").id)
Address.create(address_1: "46739 Spinning Wheel Dr", address_2: "", city: "Canton", state: "MI", postal_code: "48187", user_id: User.find_by_email("tina_fogoros@polk.com").id)
Address.create(address_1: "796 N Harvey St", address_2: "", city: "Plymouth", state: "MI", postal_code: "48170", user_id: User.find_by_email("audrey_robinson@polk.com").id)
Address.create(address_1: "1320 Ellis road", address_2: "", city: "ypsilnati", state: "MI", postal_code: "48197", user_id: User.find_by_email("duken@dteenergy.com").id)
Address.create(address_1: "33941 Coachwood Drive", address_2: "", city: "Sterling Hts", state: "MI", postal_code: "48312", user_id: User.find_by_email("jewelmick@att.net").id)
Address.create(address_1: "920 Ironwood Drive", address_2: "#343", city: "Rochester", state: "MI", postal_code: "48307", user_id: User.find_by_email("candice_belanger@yahoo.com").id)
Address.create(address_1: "1711 Lloyd Ave.", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("mmdoman@gmail.com").id)
Address.create(address_1: "10069 Boyce Road", address_2: "", city: "Chelsea", state: "MI", postal_code: "48118", user_id: User.find_by_email("esagey1@gmail.com").id)
Address.create(address_1: "13120 Oakdale", address_2: "", city: "Southgate", state: "MI", postal_code: "48195", user_id: User.find_by_email("sherry_edmunds@yahoo.com").id)
Address.create(address_1: "27096 Brush", address_2: "", city: "madison heights", state: "MI", postal_code: "48071", user_id: User.find_by_email("staceyi510@yahoo.com").id)
Address.create(address_1: "1814 Crestland St.", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("lutzj@dteenergy.com").id)
Address.create(address_1: "32370 Norchester", address_2: "", city: "Beverly Hills", state: "MI", postal_code: "48025", user_id: User.find_by_email("snanry@gmail.com").id)
Address.create(address_1: "45782 Pentwater", address_2: "", city: "Macomb", state: "MI", postal_code: "48044", user_id: User.find_by_email("jcaruso@crain.com").id)
Address.create(address_1: "16400 Levan Road", address_2: "", city: "Livonia", state: "MI", postal_code: "48154", user_id: User.find_by_email("maryann.nenninger@foresee.com").id)
Address.create(address_1: "50302 Jackson Lane", address_2: "", city: "Canton", state: "MI", postal_code: "48188", user_id: User.find_by_email("aimee.kress@foresee.com").id)
Address.create(address_1: "168 Summit View Court", address_2: "", city: "White Lake ", state: "MI", postal_code: "48386", user_id: User.find_by_email("renee.galley@foresee.com").id)
Address.create(address_1: "21345 Karr Road", address_2: "", city: "Belleville", state: "MI", postal_code: "48111", user_id: User.find_by_email("christine.baisden@foresee.com").id)
Address.create(address_1: "47638 Scenic Circle Dr N", address_2: "", city: "canton", state: "MI", postal_code: "48188", user_id: User.find_by_email("laurie.teeters@foresee.com").id)
Address.create(address_1: "1250 Library St. #42", address_2: "", city: "Detroit", state: "MI", postal_code: "48226", user_id: User.find_by_email("jane.larson@foresee.com").id)
Address.create(address_1: "5760 Katz Farm Court", address_2: "", city: "Saline", state: "MI", postal_code: "48176", user_id: User.find_by_email("lijahogan@gmail.com").id)
Address.create(address_1: "880 W Delhi Rd", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("rachel.murphy@foresee.com").id)
Address.create(address_1: "8837 Marquette Drive", address_2: "", city: "Grosse Ile", state: "MI", postal_code: "48138", user_id: User.find_by_email("brownjn@umich.edu").id)
Address.create(address_1: "9607 Edward", address_2: "", city: "Brighton", state: "MI", postal_code: "48114", user_id: User.find_by_email("kecia.brady@foresee.com").id)
Address.create(address_1: "204 Orchard View Dr.", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("svoboda01@gmail.com").id)
Address.create(address_1: "3242 Garden Ave", address_2: "", city: "royal oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("rolferchic@wowway.com").id)
Address.create(address_1: "630 S. Blair", address_2: "", city: "Royal Oak", state: "AL", postal_code: "48067", user_id: User.find_by_email("kristen.kaszeta@gmail.com").id)
Address.create(address_1: "21194 Blackmar Ave", address_2: "", city: "Warren", state: "MI", postal_code: "48091", user_id: User.find_by_email("ternstmeyer@gmail.com").id)
Address.create(address_1: "787 Monterey Ln ", address_2: "", city: "Rochester Hills", state: "MI", postal_code: "48307", user_id: User.find_by_email("juliegagliardi@kirco.com").id)
Address.create(address_1: "425 S. Main, Ste. 104", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48104", user_id: User.find_by_email("isoms@dteenergy.com").id)
Address.create(address_1: "2233 Johns Drive", address_2: "", city: "Brighton", state: "MI", postal_code: "48114", user_id: User.find_by_email("wrightk@dteenergy.com").id)
Address.create(address_1: "10037 Kress Rd", address_2: "", city: "Pinckney", state: "MI", postal_code: "48169", user_id: User.find_by_email("kirbys@dteenergy.com").id)
Address.create(address_1: "18517 Mayfield", address_2: "", city: "Livonia", state: "MI", postal_code: "48152", user_id: User.find_by_email("quinn-venturac@dteenergy.com").id)
Address.create(address_1: "23970  Waltz", address_2: "", city: "New Boston", state: "MI", postal_code: "48164", user_id: User.find_by_email("mswright_1@yahoo.com").id)
Address.create(address_1: "4890 Carrington Drive", address_2: "", city: "Rochester", state: "MI", postal_code: "48306", user_id: User.find_by_email("mksharkey@aol.com").id)
Address.create(address_1: "708  W Lincoln Ave", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48067", user_id: User.find_by_email("chris.mathews@eprize.com").id)
Address.create(address_1: "313 E 12 Mile", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("michael.daigneau@eprize.com").id)
Address.create(address_1: "360 N Batchewana", address_2: "", city: "Clawson", state: "MI", postal_code: "48017", user_id: User.find_by_email("deanaderocha@gmail.com").id)
Address.create(address_1: "10114 Kingston Ave", address_2: "", city: "Huntington Woods", state: "MI", postal_code: "48070", user_id: User.find_by_email("sarah.kahn@eprize.com").id)
Address.create(address_1: "4920 East Princeton", address_2: "", city: "Clarkston", state: "MI", postal_code: "48348", user_id: User.find_by_email("corey.case@eprize.com").id)
Address.create(address_1: "4920 E. Princeton", address_2: "", city: "Clarkston", state: "MI", postal_code: "48348", user_id: User.find_by_email("casey.brandenburg@eprize.com").id)
Address.create(address_1: "3809 Estates Drive", address_2: "", city: "Troy", state: "MI", postal_code: "48084", user_id: User.find_by_email("odonovanj@comcast.net").id)
Address.create(address_1: "121 Fieldcrest Street, Apt 102", address_2: "", city: "Ann Arbor", state: "MI", postal_code: "48103", user_id: User.find_by_email("michelle.lin@foresee.com").id)
Address.create(address_1: "25733 Forestview DR.", address_2: "", city: "Southfield", state: "MI", postal_code: "48033", user_id: User.find_by_email("ina21@att.net").id)
Address.create(address_1: "2107 Topaz Dr.", address_2: "", city: "Troy", state: "MI", postal_code: "48085", user_id: User.find_by_email("mollysings@me.com").id)
Address.create(address_1: "877 Randall Dr.", address_2: "", city: "Troy", state: "MI", postal_code: "48085", user_id: User.find_by_email("caroljeanrodriguez@gmail.com").id)
Address.create(address_1: "34336 Lakehurst", address_2: "", city: "Farmington Hills", state: "MI", postal_code: "48331", user_id: User.find_by_email("tnoribresso@twmi.rr.com").id)
Address.create(address_1: "790 Jewell St. ", address_2: "APT1", city: "Ferndale", state: "MI", postal_code: "48220", user_id: User.find_by_email("amber.york78@gmail.com").id)
Address.create(address_1: "55 North Plaza Blvd", address_2: "Apt 412", city: "Rochester Hills", state: "MI", postal_code: "48307", user_id: User.find_by_email("kristinalazuka@aol.com").id)
Address.create(address_1: "613 Chestnut Ave ", address_2: "", city: "Hazel Park", state: "MI", postal_code: "48030", user_id: User.find_by_email("tigersmeow@aol.com").id)
Address.create(address_1: "787 Monterey Lane", address_2: "", city: "Rochester Hills", state: "MI", postal_code: "48307", user_id: User.find_by_email("juliegriffin72@hotmail.com").id)
Address.create(address_1: "1529 N. Stirling", address_2: "", city: "Pontiac", state: "MI", postal_code: "48340", user_id: User.find_by_email("tkdd70@hotmail.com").id)
Address.create(address_1: "30320 Woodhouse", address_2: "", city: "Warren", state: "MI", postal_code: "48092", user_id: User.find_by_email("clakinske@aol.com").id)
Address.create(address_1: "439 Ewell St.", address_2: "", city: "Rome", state: "MI", postal_code: "48065", user_id: User.find_by_email("ruthann.stevens@yahoo.com").id)
Address.create(address_1: "27044 haverhill dr", address_2: "", city: "warren", state: "MI", postal_code: "48092", user_id: User.find_by_email("www.lizayounan@yahoo.com").id)
Address.create(address_1: "45287 Rector Drive", address_2: "", city: "Canton", state: "MI", postal_code: "48188", user_id: User.find_by_email("ogoee@dteenergy.com").id)
Address.create(address_1: "29630 Fernhill Dr.", address_2: "", city: "Farmington Hills", state: "MI", postal_code: "48334", user_id: User.find_by_email("toliosa@dteenergy.com").id)
Address.create(address_1: "28124 Diesing", address_2: "", city: "Madison Heights", state: "MI", postal_code: "48071", user_id: User.find_by_email("jcarroll@wasterecyclingnews.com").id)
