Address.create(address_1: "15536 McLain", address_2: "", city: "Allen Park", state: "MI", postal_code: "48101", user_id: User.find_by_email("wkobylarz@crain.com").id)
Address.create(address_1: "45782 Pentwater", address_2: "", city: "Macomb", state: "MI", postal_code: "48044", user_id: User.find_by_email("jcaruso@crain.com").id)
Address.create(address_1: "57 Muir", address_2: "", city: "GPF", state: "MI", postal_code: "48236", user_id: User.find_by_email("georgia_leslie@polk.com").id)
Address.create(address_1: "1333 McLean Ave.", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48067", user_id: User.find_by_email("jennserra@gmail.com").id)
Address.create(address_1: "826 N. Denwood", address_2: "", city: "Dearborn", state: "MI", postal_code: "48128", user_id: User.find_by_email("mangel@bhpnet.org").id)
Address.create(address_1: "1470 Strathcona Drive", address_2: "", city: "Detroit", state: "MI", postal_code: "48203-1464", user_id: User.find_by_email("loveh@daaa1a.org").id)
Address.create(address_1: "48626 Thorncroft", address_2: "", city: "Macomb", state: "MI", postal_code: "48044", user_id: User.find_by_email("mkozicki@crain.com").id)
Address.create(address_1: "10734 Nadine Ave", address_2: "", city: "Huntington Woods", state: "MI", postal_code: "48070", user_id: User.find_by_email("tshagar@hotmail.com").id)
Address.create(address_1: "53250 Beechwood Dr", address_2: "", city: "Shelby Twp", state: "MI", postal_code: "48316", user_id: User.find_by_email("dnied@bhpnet.org").id)
Address.create(address_1: "28266 Groveland", address_2: "", city: "Madison Heights", state: "MI", postal_code: "48071", user_id: User.find_by_email("n_rockey@hotmail.com").id)
Address.create(address_1: "2436 Maplewood Ave", address_2: "", city: "Royal Oak", state: "MI", postal_code: "48073", user_id: User.find_by_email("joyx@comcast.net").id)
Address.create(address_1: "2104 Coy", address_2: "", city: "Ferndale", state: "MI", postal_code: "48220", user_id: User.find_by_email("kmdowhan@yahoo.com").id)
