ClientGroup.create(id: 2, code: "ADULT01", title: "Adult")
ClientGroup.create(id: 3, code: "YOUTH01", title: "Youth")
ClientGroup.create(id: 4, code: "SPECIALN01", title: "Special Needs")
ClientGroup.create(id: 7, code: "PSI2012", title: "Phillip Service Industries")
ClientGroup.create(id: 8, code: "TD2012", title: "Team Detroit")
ClientGroup.create(id: 9, code: "DTE2012", title: "DTE Energy ")
ClientGroup.create(id: 10, code: "MAGP2012", title: "Magna Powertrain")
ClientGroup.create(id: 11, code: "MERI2012", title: "Meritor")
ClientGroup.create(id: 12, code: "KIR2012", title: "Kirco")
ClientGroup.create(id: 13, code: "FCMA2012", title: "Four Corners Montessori Academy")
ClientGroup.create(id: 14, code: "FedAPD2012", title: "Federal APD")
ClientGroup.create(id: 15, code: "ASOC2012", title: "Autism Society Oakland County")
ClientGroup.create(id: 17, code: "BPark2012", title: "Brewery Park ")
ClientGroup.create(id: 19, code: "POLK2012", title: "POLK")
ClientGroup.create(id: 20, code: "TEST01", title: "Test Account")
ClientGroup.create(id: 21, code: "GSBecker", title: "Becker Elementary Girl Scouts")
ClientGroup.create(id: 22, code: "GSBecker", title: "Becker Elementary Girl Scouts")
ClientGroup.create(id: 23, code: "ASK2012 ", title: "Autism ASK ")
ClientGroup.create(id: 24, code: "DTE2012", title: "Belightful Yoga ")
ClientGroup.create(id: 25, code: "Brown2012", title: "Brown")
ClientGroup.create(id: 26, code: "OCEF2012", title: "Oakwood CEF")
ClientGroup.create(id: 27, code: "39533", title: "39533 Woodward ")
ClientGroup.create(id: 28, code: "FSR2012", title: "Foresee Results")
ClientGroup.create(id: 29, code: "MISDYoga", title: "Macomb Intermediate School District")
ClientGroup.create(id: 30, code: "JD2012", title: "Judson Center ")
ClientGroup.create(id: 31, code: "BOMA2012", title: "BOMA Belightful Yoga Event")
ClientGroup.create(id: 32, code: "DSGteens", title: "Down Syndrome Guild Teen Yoga")
ClientGroup.create(id: 33, code: "EP2013", title: "ePrize")
ClientGroup.create(id: 34, code: "FSR2012", title: "")
ClientGroup.create(id: 35, code: "FSR2012", title: "")
