ClientGroup.create(code: "ADULT01", title: "Adult")
ClientGroup.create(code: "YOUTH01", title: "Youth")
ClientGroup.create(code: "SPECIALN01", title: "Special Needs")
ClientGroup.create(code: "PSI2012", title: "Phillip Service Industries")
ClientGroup.create(code: "TD2012", title: "Team Detroit")
ClientGroup.create(code: "DTE2012", title: "DTE Energy ")
ClientGroup.create(code: "MAGP2012", title: "Magna Powertrain")
ClientGroup.create(code: "MERI2012", title: "Meritor")
ClientGroup.create(code: "KIR2012", title: "Kirco")
ClientGroup.create(code: "FCMA2012", title: "Four Corners Montessori Academy")
ClientGroup.create(code: "FedAPD2012", title: "Federal APD")
ClientGroup.create(code: "ASOC2012", title: "Autism Society Oakland County")
ClientGroup.create(code: "BPark2012", title: "Brewery Park ")
ClientGroup.create(code: "POLK2012", title: "POLK")
ClientGroup.create(code: "TEST01", title: "Test Account")
ClientGroup.create(code: "GSBecker", title: "Becker Elementary Girl Scouts")
ClientGroup.create(code: "ASK2012 ", title: "Autism ASK ")
ClientGroup.create(code: "Brown2012", title: "Brown")
ClientGroup.create(code: "OCEF2012", title: "Oakwood CEF")
ClientGroup.create(code: "39533", title: "39533 Woodward ")
ClientGroup.create(code: "FSR2012", title: "Foresee Results")
ClientGroup.create(code: "MISDYoga", title: "Macomb Intermediate School District")
ClientGroup.create(code: "JD2012", title: "Judson Center ")
ClientGroup.create(code: "BOMA2012", title: "BOMA Belightful Yoga Event")
ClientGroup.create(code: "DSGteens", title: "Down Syndrome Guild Teen Yoga")
ClientGroup.create(code: "EP2013", title: "ePrize")
