User.create(email: "jacquitap@yahoo.com", password: "Christ", password_confirmation: "Christ", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "JACQUITA", middle_initial: "", last_name: "PICKETT", address_1: "20035 AVON", address_2: "", city: "DETROIT", state: "MI", zip: "48219", home_phone: "", work_phone: "", work_phone_ext: "", cell_phone: "313-520-2154", occupation: "", emergency_contact: "", birthdate: nil)
User.create(email: "krystyna_secunda@polk.com", password: "nick1507", password_confirmation: "nick1507", client_group_id: ClientGroup.find_by_code("POLK2012").id, first_name: "", middle_initial: "", last_name: "", address_1: "", address_2: "", city: "", state: "", zip: "", home_phone: "", work_phone: "", work_phone_ext: "", cell_phone: "", occupation: "", emergency_contact: "", birthdate: nil)
User.create(email: "jennserra@gmail.com", password: "j2c67896", password_confirmation: "j2c67896", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "Serra", middle_initial: "C", last_name: "Jenn", address_1: "1333 McLean Ave.", address_2: "", city: "Royal Oak", state: "MI", zip: "48067", home_phone: "269.352.3723", work_phone: "313.656.0092", work_phone_ext: "", cell_phone: "269-352-3723", occupation: "HR Coordinator", emergency_contact: "Debbie Serra, 586.634.0222, Mom", birthdate: nil)
User.create(email: "mangel@bhpnet.org", password: "newlife1", password_confirmation: "newlife1", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "Marisol", middle_initial: "", last_name: "Angel", address_1: "826 N. Denwood", address_2: "", city: "Dearborn", state: "MI", zip: "48128", home_phone: "313-304-7832", work_phone: "313-304-7832", work_phone_ext: "", cell_phone: "313-304-7832", occupation: "Supervisor", emergency_contact: "JJ Quesada, 313-401-6899", birthdate: nil)
User.create(email: "prhodes@crain.com", password: "raven98", password_confirmation: "raven98", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "", middle_initial: "", last_name: "", address_1: "", address_2: "", city: "", state: "", zip: "", home_phone: "", work_phone: "", work_phone_ext: "", cell_phone: "", occupation: "", emergency_contact: "", birthdate: nil)
User.create(email: "loveh@daaa1a.org", password: "yoga197094", password_confirmation: "yoga197094", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "Helen", middle_initial: "B", last_name: "Love", address_1: "1470 Strathcona Drive", address_2: "", city: "Detroit", state: "MI", zip: "48203-1464", home_phone: "313-368-0068", work_phone: "313-446-4444", work_phone_ext: "5858", cell_phone: "313-506-1470 (preferred)", occupation: "PR Specialist", emergency_contact: "Karla Morris, Friend, 313-319-9638", birthdate: nil)
User.create(email: "tshagar@hotmail.com", password: "pigwidgeon", password_confirmation: "pigwidgeon", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "Tamara", middle_initial: "S", last_name: "Hagar", address_1: "10734 Nadine Ave", address_2: "", city: "Huntington Woods", state: "MI", zip: "48070", home_phone: "248-677-3786", work_phone: "313-656-0052", work_phone_ext: "", cell_phone: "248-828-5737", occupation: "", emergency_contact: "Kosta Papanikolaou 313-805-5616 husband", birthdate: "1975-02-21")
User.create(email: "dnied@bhpnet.org", password: "winter212013", password_confirmation: "winter212013", client_group_id: ClientGroup.find_by_code("BPark2012").id, first_name: "Doreen", middle_initial: "M.", last_name: "Nied", address_1: "53250 Beechwood Dr", address_2: "", city: "Shelby Twp", state: "MI", zip: "48316", home_phone: "586 453 3018", work_phone: "313- 65-6 00", work_phone_ext: "", cell_phone: "", occupation: "Exec Director", emergency_contact: "David Nied - spouse - 586 453 3019", birthdate: nil)
User.create(email: "n_rockey@hotmail.com", password: "MzKQb85i", password_confirmation: "MzKQb85i", client_group_id: ClientGroup.find_by_code("FCMA2012").id, first_name: "Nora", middle_initial: "", last_name: "Cash", address_1: "28266 Groveland", address_2: "", city: "Madison Heights", state: "MI", zip: "48071", home_phone: "none", work_phone: "313-225-6393", work_phone_ext: "", cell_phone: "248-561-7782", occupation: "student", emergency_contact: "Mother- Nora Cash- see phone numbers above", birthdate: "2005-11-20")
User.create(email: "joyx@comcast.net", password: "yogamoop", password_confirmation: "yogamoop", client_group_id: ClientGroup.find_by_code("FCMA2012").id, first_name: "Suzanne", middle_initial: "", last_name: "Joy", address_1: "2436 Maplewood Ave", address_2: "", city: "Royal Oak", state: "MI", zip: "48073", home_phone: "2482883735", work_phone: "2482883735", work_phone_ext: "", cell_phone: "248-288-3735", occupation: "", emergency_contact: "Suzanne Joy, 248-288-3735, MotherScott Joy, 248-996-7711", birthdate: nil)
User.create(email: "KMDowhan@yahoo.com", password: "jeepers1", password_confirmation: "jeepers1", client_group_id: ClientGroup.find_by_code("FCMA2012").id, first_name: "Jackson", middle_initial: "D", last_name: "Dowhan", address_1: "2104 Coy", address_2: "", city: "Ferndale", state: "MI", zip: "48220", home_phone: "248-691-4238", work_phone: "", work_phone_ext: "", cell_phone: "", occupation: "", emergency_contact: "Dave Dowhan 248-506-3735cell--dadKristine Dowhan 248-266-8888wk  248-722-4899 cell  moother", birthdate: nil)
