development:
  adapter: postgresql
  encoding: unicode
  database: belightfulyoga_development
  pool: 5
  username: belightfulyoga
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: belightfulyoga_test
  pool: 5
  username: belightfulyoga
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: belightfulyoga_production
  pool: 5
  username: belightfulyoga
  password:
